// ==================== ДАННЫЕ ТОВАРОВ ====================

// Игры (15 штук)
const games = [
    {
        id: 1,
        name: "Cyberpunk 2077",
        category: "games",
        subcategory: "rpg",
        categoryName: "Игры",
        price: 1990,
        oldPrice: 2990,
        discount: 33,
        rating: 4.5,
        reviews: 12500,
        image: "gamepad",
        badge: "popular",
        platform: "PC",
        genre: "RPG",
        description: "Ролевая игра в открытом мире от CD Projekt Red"
    },
    {
        id: 2,
        name: "Baldur's Gate 3",
        category: "games",
        subcategory: "rpg",
        categoryName: "Игры",
        price: 2490,
        oldPrice: 3490,
        discount: 28,
        rating: 5.0,
        reviews: 8760,
        image: "dragon",
        badge: "new",
        platform: "PC",
        genre: "RPG",
        description: "Ролевая игра года по версии The Game Awards"
    },
    {
        id: 3,
        name: "Red Dead Redemption 2",
        category: "games",
        subcategory: "action",
        categoryName: "Игры",
        price: 2290,
        oldPrice: 3990,
        discount: 42,
        rating: 4.9,
        reviews: 15600,
        image: "horse",
        badge: "popular",
        platform: "PC",
        genre: "Action",
        description: "Вестерн в открытом мире от Rockstar Games"
    },
    {
        id: 4,
        name: "Microsoft Flight Simulator 2024",
        category: "games",
        subcategory: "simulator",
        categoryName: "Игры",
        price: 3990,
        oldPrice: 5990,
        discount: 33,
        rating: 4.7,
        reviews: 3450,
        image: "plane",
        badge: "new",
        platform: "PC",
        genre: "Симулятор",
        description: "Самый реалистичный авиасимулятор"
    },
    {
        id: 5,
        name: "The Witcher 3: Wild Hunt",
        category: "games",
        subcategory: "rpg",
        categoryName: "Игры",
        price: 1490,
        oldPrice: 2990,
        discount: 50,
        rating: 4.9,
        reviews: 23400,
        image: "hat-wizard",
        badge: "sale",
        platform: "PC",
        genre: "RPG",
        description: "Легендарная ролевая игра с дополнениями"
    },
    {
        id: 6,
        name: "Call of Duty: Modern Warfare III",
        category: "games",
        subcategory: "action",
        categoryName: "Игры",
        price: 3990,
        oldPrice: 5990,
        discount: 33,
        rating: 4.3,
        reviews: 8900,
        image: "gun",
        badge: "new",
        platform: "PC",
        genre: "Шутер",
        description: "Новая часть культового шутера"
    },
    {
        id: 7,
        name: "Cities: Skylines II",
        category: "games",
        subcategory: "simulator",
        categoryName: "Игры",
        price: 2990,
        oldPrice: 4490,
        discount: 33,
        rating: 4.6,
        reviews: 5600,
        image: "city",
        badge: "popular",
        platform: "PC",
        genre: "Градостроительный симулятор",
        description: "Лучший градостроительный симулятор"
    },
    {
        id: 8,
        name: "Starfield",
        category: "games",
        subcategory: "rpg",
        categoryName: "Игры",
        price: 3490,
        oldPrice: 4990,
        discount: 30,
        rating: 4.4,
        reviews: 12300,
        image: "rocket",
        badge: "new",
        platform: "PC",
        genre: "RPG",
        description: "Космическая RPG от Bethesda"
    },
    {
        id: 9,
        name: "EA Sports FC 24",
        category: "games",
        subcategory: "simulator",
        categoryName: "Игры",
        price: 2990,
        oldPrice: 4490,
        discount: 33,
        rating: 4.2,
        reviews: 7800,
        image: "futbol",
        badge: "popular",
        platform: "PC",
        genre: "Спортивный симулятор",
        description: "Новый футбольный симулятор"
    },
    {
        id: 10,
        name: "Hogwarts Legacy",
        category: "games",
        subcategory: "rpg",
        categoryName: "Игры",
        price: 2790,
        oldPrice: 3990,
        discount: 30,
        rating: 4.8,
        reviews: 15600,
        image: "hat-wizard",
        badge: "popular",
        platform: "PC",
        genre: "RPG",
        description: "Игра в мире Гарри Поттера"
    },
    {
        id: 11,
        name: "Diablo IV",
        category: "games",
        subcategory: "rpg",
        categoryName: "Игры",
        price: 3490,
        oldPrice: 4990,
        discount: 30,
        rating: 4.5,
        reviews: 9800,
        image: "skull",
        badge: "popular",
        platform: "PC",
        genre: "Action RPG",
        description: "Мрачная action-RPG от Blizzard"
    },
    {
        id: 12,
        name: "Farming Simulator 24",
        category: "games",
        subcategory: "simulator",
        categoryName: "Игры",
        price: 1990,
        oldPrice: 2990,
        discount: 33,
        rating: 4.3,
        reviews: 3400,
        image: "tractor",
        badge: "new",
        platform: "PC",
        genre: "Симулятор",
        description: "Реалистичный фермерский симулятор"
    },
    {
        id: 13,
        name: "Assassin's Creed Mirage",
        category: "games",
        subcategory: "action",
        categoryName: "Игры",
        price: 2490,
        oldPrice: 3990,
        discount: 37,
        rating: 4.4,
        reviews: 6700,
        image: "mask",
        badge: "new",
        platform: "PC",
        genre: "Action",
        description: "Новая часть Assassin's Creed"
    },
    {
        id: 14,
        name: "Euro Truck Simulator 3",
        category: "games",
        subcategory: "simulator",
        categoryName: "Игры",
        price: 1490,
        oldPrice: 2490,
        discount: 40,
        rating: 4.7,
        reviews: 8900,
        image: "truck",
        badge: "popular",
        platform: "PC",
        genre: "Симулятор",
        description: "Симулятор дальнобойщика по Европе"
    },
    {
        id: 15,
        name: "S.T.A.L.K.E.R. 2",
        category: "games",
        subcategory: "action",
        categoryName: "Игры",
        price: 2990,
        oldPrice: 4490,
        discount: 33,
        rating: 4.6,
        reviews: 4500,
        image: "radiation",
        badge: "new",
        platform: "PC",
        genre: "Шутер",
        description: "Долгожданное продолжение культовой игры"
    }
];

// Программы (15 штук)
const software = [
    {
        id: 101,
        name: "Adobe Photoshop 2024",
        category: "software",
        subcategory: "graphics",
        categoryName: "Программы",
        price: 2990,
        oldPrice: 5990,
        discount: 50,
        rating: 4.8,
        reviews: 3420,
        image: "paint-brush",
        badge: "popular",
        platform: "Windows/Mac",
        description: "Профессиональный редактор изображений"
    },
    {
        id: 102,
        name: "Adobe Premiere Pro 2024",
        category: "software",
        subcategory: "graphics",
        categoryName: "Программы",
        price: 3490,
        oldPrice: 6990,
        discount: 50,
        rating: 4.7,
        reviews: 2800,
        image: "video",
        badge: "popular",
        platform: "Windows/Mac",
        description: "Профессиональный видеоредактор"
    },
    {
        id: 103,
        name: "Microsoft Office 2024 Pro",
        category: "software",
        subcategory: "office",
        categoryName: "Программы",
        price: 3990,
        oldPrice: 7990,
        discount: 50,
        rating: 4.9,
        reviews: 12500,
        image: "file-alt",
        badge: "popular",
        platform: "Windows/Mac",
        description: "Word, Excel, PowerPoint, Outlook"
    },
    {
        id: 104,
        name: "Visual Studio 2024 Pro",
        category: "software",
        subcategory: "development",
        categoryName: "Программы",
        price: 4490,
        oldPrice: 8990,
        discount: 50,
        rating: 4.8,
        reviews: 5600,
        image: "code",
        badge: "new",
        platform: "Windows",
        description: "Среда разработки от Microsoft"
    },
    {
        id: 105,
        name: "Adobe Illustrator 2024",
        category: "software",
        subcategory: "graphics",
        categoryName: "Программы",
        price: 2990,
        oldPrice: 5990,
        discount: 50,
        rating: 4.7,
        reviews: 2300,
        image: "pen",
        badge: "popular",
        platform: "Windows/Mac",
        description: "Векторная графика и иллюстрации"
    },
    {
        id: 106,
        name: "AutoCAD 2024",
        category: "software",
        subcategory: "graphics",
        categoryName: "Программы",
        price: 4990,
        oldPrice: 9990,
        discount: 50,
        rating: 4.6,
        reviews: 1800,
        image: "draw-polygon",
        badge: "professional",
        platform: "Windows",
        description: "САПР для проектирования"
    },
    {
        id: 107,
        name: "3ds Max 2024",
        category: "software",
        subcategory: "graphics",
        categoryName: "Программы",
        price: 5490,
        oldPrice: 10990,
        discount: 50,
        rating: 4.5,
        reviews: 1200,
        image: "cube",
        badge: "professional",
        platform: "Windows",
        description: "3D моделирование и анимация"
    },
    {
        id: 108,
        name: "JetBrains IntelliJ IDEA",
        category: "software",
        subcategory: "development",
        categoryName: "Программы",
        price: 2490,
        oldPrice: 4990,
        discount: 50,
        rating: 4.9,
        reviews: 3400,
        image: "java",
        badge: "popular",
        platform: "Windows/Mac/Linux",
        description: "IDE для Java разработки"
    },
    {
        id: 109,
        name: "PyCharm Professional",
        category: "software",
        subcategory: "development",
        categoryName: "Программы",
        price: 1990,
        oldPrice: 3990,
        discount: 50,
        rating: 4.8,
        reviews: 2900,
        image: "python",
        badge: "popular",
        platform: "Windows/Mac/Linux",
        description: "IDE для Python разработки"
    },
    {
        id: 110,
        name: "CorelDRAW Graphics Suite",
        category: "software",
        subcategory: "graphics",
        categoryName: "Программы",
        price: 3290,
        oldPrice: 6590,
        discount: 50,
        rating: 4.6,
        reviews: 1500,
        image: "pen",
        badge: "popular",
        platform: "Windows",
        description: "Графический дизайн и верстка"
    },
    {
        id: 111,
        name: "VMware Workstation Pro",
        category: "software",
        subcategory: "development",
        categoryName: "Программы",
        price: 2990,
        oldPrice: 5990,
        discount: 50,
        rating: 4.7,
        reviews: 1100,
        image: "server",
        badge: "professional",
        platform: "Windows/Linux",
        description: "Виртуализация ОС"
    },
    {
        id: 112,
        name: "Adobe After Effects 2024",
        category: "software",
        subcategory: "graphics",
        categoryName: "Программы",
        price: 3490,
        oldPrice: 6990,
        discount: 50,
        rating: 4.7,
        reviews: 2100,
        image: "film",
        badge: "popular",
        platform: "Windows/Mac",
        description: "Создание видеоэффектов и анимации"
    },
    {
        id: 113,
        name: "Microsoft Project 2024",
        category: "software",
        subcategory: "office",
        categoryName: "Программы",
        price: 2990,
        oldPrice: 5990,
        discount: 50,
        rating: 4.5,
        reviews: 800,
        image: "tasks",
        badge: "professional",
        platform: "Windows",
        description: "Управление проектами"
    },
    {
        id: 114,
        name: "MATLAB R2024",
        category: "software",
        subcategory: "development",
        categoryName: "Программы",
        price: 5990,
        oldPrice: 11990,
        discount: 50,
        rating: 4.6,
        reviews: 950,
        image: "calculator",
        badge: "professional",
        platform: "Windows/Mac/Linux",
        description: "Численные вычисления и моделирование"
    },
    {
        id: 115,
        name: "DAVINCI Resolve Studio",
        category: "software",
        subcategory: "graphics",
        categoryName: "Программы",
        price: 2790,
        oldPrice: 5590,
        discount: 50,
        rating: 4.8,
        reviews: 1700,
        image: "video",
        badge: "popular",
        platform: "Windows/Mac/Linux",
        description: "Профессиональный видеомонта
