// ==================== ДАННЫЕ ТОВАРОВ ====================

// Категории для главной страницы
const categories = [
    { id: "steam-games", name: "Игры Steam", icon: "steam", count: 50 },
    { id: "subscriptions", name: "Подписки", icon: "crown", count: 30 },
    { id: "software", name: "Программы", icon: "laptop-code", count: 40 },
    { id: "antivirus", name: "Антивирусы", icon: "shield-alt", count: 25 },
    { id: "steam-balance", name: "Пополнение Steam", icon: "wallet", count: 10 }
];

// Игры Steam (30+ игр)
const steamGames = [
    // Топ игры
    {
        id: 1,
        name: "Counter-Strike 2",
        category: "steam-games",
        subcategory: "top",
        categoryName: "Игры Steam",
        price: 0,
        oldPrice: 0,
        discount: 0,
        rating: 4.9,
        reviews: 250000,
        image: "crosshairs",
        badge: "popular",
        platform: "Steam",
        genre: "Шутер",
        description: "Бесплатная игра. Внутриигровые предметы."
    },
    {
        id: 2,
        name: "Dota 2",
        category: "steam-games",
        subcategory: "top",
        categoryName: "Игры Steam",
        price: 0,
        oldPrice: 0,
        discount: 0,
        rating: 4.8,
        reviews: 180000,
        image: "chess-queen",
        badge: "popular",
        platform: "Steam",
        genre: "MOBA",
        description: "Бесплатная игра. Внутриигровые предметы."
    },
    {
        id: 3,
        name: "PUBG: BATTLEGROUNDS",
        category: "steam-games",
        subcategory: "top",
        categoryName: "Игры Steam",
        price: 1290,
        oldPrice: 1990,
        discount: 35,
        rating: 4.5,
        reviews: 89000,
        image: "gun",
        badge: "sale",
        platform: "Steam",
        genre: "Королевская битва",
        description: "Ключ PUBG для Steam"
    },
    {
        id: 4,
        name: "Apex Legends",
        category: "steam-games",
        subcategory: "top",
        categoryName: "Игры Steam",
        price: 0,
        oldPrice: 0,
        discount: 0,
        rating: 4.6,
        reviews: 67000,
        image: "bolt",
        badge: "popular",
        platform: "Steam",
        genre: "Королевская битва",
        description: "Бесплатная игра. Монеты Apex."
    },
    {
        id: 5,
        name: "Cyberpunk 2077",
        category: "steam-games",
        subcategory: "top",
        categoryName: "Игры Steam",
        price: 1990,
        oldPrice: 2990,
        discount: 33,
        rating: 4.5,
        reviews: 125000,
        image: "gamepad",
        badge: "sale",
        platform: "Steam",
        genre: "RPG",
        description: "Ключ Cyberpunk 2077 для Steam"
    },
    {
        id: 6,
        name: "Baldur's Gate 3",
        category: "steam-games",
        subcategory: "top",
        categoryName: "Игры Steam",
        price: 2490,
        oldPrice: 3490,
        discount: 28,
        rating: 5.0,
        reviews: 87600,
        image: "dragon",
        badge: "popular",
        platform: "Steam",
        genre: "RPG",
        description: "Ключ Baldur's Gate 3 для Steam"
    },
    {
        id: 7,
        name: "Red Dead Redemption 2",
        category: "steam-games",
        subcategory: "top",
        categoryName: "Игры Steam",
        price: 2290,
        oldPrice: 3990,
        discount: 42,
        rating: 4.9,
        reviews: 156000,
        image: "horse",
        badge: "sale",
        platform: "Steam",
        genre: "Action",
        description: "Ключ RDR2 для Steam"
    },
    {
        id: 8,
        name: "Elden Ring",
        category: "steam-games",
        subcategory: "top",
        categoryName: "Игры Steam",
        price: 2790,
        oldPrice: 3990,
        discount: 30,
        rating: 4.9,
        reviews: 98000,
        image: "crown",
        badge: "popular",
        platform: "Steam",
        genre: "RPG",
        description: "Ключ Elden Ring для Steam"
    },
    // Новинки
    {
        id: 9,
        name: "Hogwarts Legacy",
        category: "steam-games",
        subcategory: "new",
        categoryName: "Игры Steam",
        price: 2790,
        oldPrice: 3990,
        discount: 30,
        rating: 4.8,
        reviews: 156000,
        image: "hat-wizard",
        badge: "new",
        platform: "Steam",
        genre: "RPG",
        description: "Ключ Hogwarts Legacy для Steam"
    },
    {
        id: 10,
        name: "Diablo IV",
        category: "steam-games",
        subcategory: "new",
        categoryName: "Игры Steam",
        price: 3490,
        oldPrice: 4990,
        discount: 30,
        rating: 4.5,
        reviews: 98000,
        image: "skull",
        badge: "new",
        platform: "Steam",
        genre: "RPG",
        description: "Ключ Diablo IV для Steam"
    },
    {
        id: 11,
        name: "Starfield",
        category: "steam-games",
        subcategory: "new",
        categoryName: "Игры Steam",
        price: 3490,
        oldPrice: 4990,
        discount: 30,
        rating: 4.4,
        reviews: 123000,
        image: "rocket",
        badge: "new",
        platform: "Steam",
        genre: "RPG",
        description: "Ключ Starfield для Steam"
    },
    {
        id: 12,
        name: "S.T.A.L.K.E.R. 2",
        category: "steam-games",
        subcategory: "new",
        categoryName: "Игры Steam",
        price: 2990,
        oldPrice: 4490,
        discount: 33,
        rating: 4.6,
        reviews: 45000,
        image: "radiation",
        badge: "new",
        platform: "Steam",
        genre: "Шутер",
        description: "Ключ S.T.A.L.K.E.R. 2"
    },
    {
        id: 13,
        name: "Cities: Skylines II",
        category: "steam-games",
        subcategory: "new",
        categoryName: "Игры Steam",
        price: 2990,
        oldPrice: 4490,
        discount: 33,
        rating: 4.6,
        reviews: 56000,
        image: "city",
        badge: "new",
        platform: "Steam",
        genre: "Симулятор",
        description: "Ключ Cities Skylines 2"
    },
    {
        id: 14,
        name: "Microsoft Flight Simulator 2024",
        category: "steam-games",
        subcategory: "new",
        categoryName: "Игры Steam",
        price: 3990,
        oldPrice: 5990,
        discount: 33,
        rating: 4.7,
        reviews: 34500,
        image: "plane",
        badge: "new",
        platform: "Steam",
        genre: "Симулятор",
        description: "Ключ Flight Simulator 2024"
    },
    // Со скидкой
    {
        id: 15,
        name: "The Witcher 3: Wild Hunt",
        category: "steam-games",
        subcategory: "sale",
        categoryName: "Игры Steam",
        price: 1490,
        oldPrice: 2990,
        discount: 50,
        rating: 4.9,
        reviews: 234000,
        image: "hat-wizard",
        badge: "sale",
        platform: "Steam",
        genre: "RPG",
        description: "GOTY издание с дополнениями"
    },
    {
        id: 16,
        name: "Grand Theft Auto V",
        category: "steam-games",
        subcategory: "sale",
        categoryName: "Игры Steam",
        price: 1490,
        oldPrice: 2990,
        discount: 50,
        rating: 4.8,
        reviews: 198000,
        image: "car",
        badge: "sale",
        platform: "Steam",
        genre: "Action",
        description: "GTA V Premium Edition"
    },
    {
        id: 17,
        name: "EA Sports FC 24",
        category: "steam-games",
        subcategory: "sale",
        categoryName: "Игры Steam",
        price: 2990,
        oldPrice: 4490,
        discount: 33,
        rating: 4.2,
        reviews: 78000,
        image: "futbol",
        badge: "sale",
        platform: "Steam",
        genre: "Спорт",
        description: "Ключ EA FC 24"
    },
    {
        id: 18,
        name: "Assassin's Creed Mirage",
        category: "steam-games",
        subcategory: "sale",
        categoryName: "Игры Steam",
        price: 2490,
        oldPrice: 3990,
        discount: 37,
        rating: 4.4,
        reviews: 67000,
        image: "mask",
        badge: "sale",
        platform: "Steam",
        genre: "Action",
        description: "Ключ Assassin's Creed Mirage"
    },
    {
        id: 19,
        name: "Farming Simulator 24",
        category: "steam-games",
        subcategory: "sale",
        categoryName: "Игры Steam",
        price: 1990,
        oldPrice: 2990,
        discount: 33,
        rating: 4.3,
        reviews: 34000,
        image: "tractor",
        badge: "sale",
        platform: "Steam",
        genre: "Симулятор",
        description: "Ключ Farming Simulator 24"
    },
    {
        id: 20,
        name: "Euro Truck Simulator 3",
        category: "steam-games",
        subcategory: "sale",
        categoryName: "Игры Steam",
        price: 1490,
        oldPrice: 2490,
        discount: 40,
        rating: 4.7,
        reviews: 89000,
        image: "truck",
        badge: "sale",
        platform: "Steam",
        genre: "Симулятор",
        description: "Ключ ETS 3"
    },
    {
        id: 21,
        name: "Rainbow Six Siege",
        category: "steam-games",
        subcategory: "sale",
        categoryName: "Игры Steam",
        price: 990,
        oldPrice: 1990,
        discount: 50,
        rating: 4.5,
        reviews: 156000,
        image: "user-secret",
        badge: "sale",
        platform: "Steam",
        genre: "Шутер",
        description: "Ключ R6 Siege"
    },
    {
        id: 22,
        name: "Call of Duty: Modern Warfare III",
        category: "steam-games",
        subcategory: "top",
        categoryName: "Игры Steam",
        price: 3990,
        oldPrice: 5990,
        discount: 33,
        rating: 4.3,
        reviews: 89000,
        image: "gun",
        badge: "new",
        platform: "Steam",
        genre: "Шутер",
        description: "Ключ COD MW3 для Steam"
    },
    {
        id: 23,
        name: "Battlefield 2042",
        category: "steam-games",
        subcategory: "sale",
        categoryName: "Игры Steam",
        price: 1490,
        oldPrice: 2990,
        discount: 50,
        rating: 4.0,
        reviews: 45000,
        image: "gun",
        badge: "sale",
        platform: "Steam",
        genre: "Шутер",
        description: "Ключ Battlefield 2042"
    },
    {
        id: 24,
        name: "ARK: Survival Ascended",
        category: "steam-games",
        subcategory: "new",
        categoryName: "Игры Steam",
        price: 2490,
        oldPrice: 3490,
        discount: 28,
        rating: 4.5,
        reviews: 23000,
        image: "dragon",
        badge: "new",
        platform: "Steam",
        genre: "Выживание",
        description: "Ключ ARK: Survival Ascended"
    },
    {
        id: 25,
        name: "Palworld",
        category: "steam-games",
        subcategory: "top",
        categoryName: "Игры Steam",
        price: 1290,
        oldPrice: 1990,
        discount: 35,
        rating: 4.7,
        reviews: 189000,
        image: "paw",
        badge: "popular",
        platform: "Steam",
        genre: "Выживание",
        description: "Ключ Palworld"
    },
    {
        id: 26,
        name: "Helldivers 2",
        category: "steam-games",
        subcategory: "top",
        categoryName: "Игры Steam",
        price: 2490,
        oldPrice: 2990,
        discount: 16,
        rating: 4.8,
        reviews: 134000,
        image: "gun",
        badge: "popular",
        platform: "Steam",
        genre: "Шутер",
        description: "Ключ Helldivers 2"
    },
    {
        id: 27,
        name: "Dragon's Dogma 2",
        category: "steam-games",
        subcategory: "new",
        categoryName: "Игры Steam",
        price: 3490,
        oldPrice: 4490,
        discount: 22,
        rating: 4.5,
        reviews: 34000,
        image: "dragon",
        badge: "new",
        platform: "Steam",
        genre: "RPG",
        description: "Ключ Dragon's Dogma 2"
    },
    {
        id: 28,
        name: "Last Epoch",
        category: "steam-games",
        subcategory: "top",
        categoryName: "Игры Steam",
        price: 1990,
        oldPrice: 2490,
        discount: 20,
        rating: 4.6,
        reviews: 43000,
        image: "skull",
        badge: "popular",
        platform: "Steam",
        genre: "RPG",
        description: "Ключ Last Epoch"
    },
    {
        id: 29,
        name: "Enshrouded",
        category: "steam-games",
        subcategory: "new",
        categoryName: "Игры Steam",
        price: 1990,
        oldPrice: 2490,
        discount: 20,
        rating: 4.7,
        reviews: 28000,
        image: "mountain",
        badge: "new",
        platform: "Steam",
        genre: "Выживание",
        description: "Ключ Enshrouded"
    },
    {
        id: 30,
        name: "Nightingale",
        category: "steam-games",
        subcategory: "new",
        categoryName: "Игры Steam",
        price: 1990,
        oldPrice: 2490,
        discount: 20,
        rating: 4.3,
        reviews: 12000,
        image: "feather",
        badge: "new",
        platform: "Steam",
        genre: "Выживание",
        description: "Ключ Nightingale"
    }
];

// Подписки (20 подписок)
const subscriptions = [
    {
        id: 101,
        name: "Discord Nitro Classic",
        category: "subscriptions",
        subcategory: "discord",
        categoryName: "Подписки",
        price: 299,
        oldPrice: 499,
        discount: 40,
        rating: 4.8,
        reviews: 3400,
        image: "discord",
        badge: "popular",
        platform: "Discord",
        period: "1 месяц",
        description: "Discord Nitro Classic подписка"
    },
    {
        id: 102,
        name: "Discord Nitro Full",
        category: "subscriptions",
        subcategory: "discord",
        categoryName: "Подписки",
        price: 599,
        oldPrice: 999,
        discount: 40,
        rating: 4.9,
        reviews: 5600,
        image: "discord",
        badge: "popular",
        platform: "Discord",
        period: "1 месяц",
        description: "Discord Nitro полная подписка"
    },
    {
        id: 103,
        name: "Telegram Premium",
        category: "subscriptions",
        subcategory: "telegram",
        categoryName: "Подписки",
        price: 299,
        oldPrice: 499,
        discount: 40,
        rating: 4.7,
        reviews: 8900,
        image: "telegram",
        badge: "new",
        platform: "Telegram",
        period: "1 месяц",
        description: "Telegram Premium подписка"
    },
    {
        id: 104,
        name: "Яндекс Музыка",
        category: "subscriptions",
        subcategory: "music",
        categoryName: "Подписки",
        price: 199,
        oldPrice: 299,
        discount: 33,
        rating: 4.6,
        reviews: 12300,
        image: "music",
        badge: "popular",
        platform: "Яндекс",
        period: "1 месяц",
        description: "Яндекс Музыка подписка"
    },
    {
        id: 105,
        name: "Яндекс Плюс",
        category: "subscriptions",
        subcategory: "music",
        categoryName: "Подписки",
        price: 299,
        oldPrice: 499,
        discount: 40,
        rating: 4.7,
        reviews: 15600,
        image: "plus-circle",
        badge: "popular",
        platform: "Яндекс",
        period: "1 месяц",
        description: "Яндекс Плюс (Музыка + Кинопоиск)"
    },
    {
        id: 106,
        name: "VK Combo",
        category: "subscriptions",
        subcategory: "music",
        categoryName: "Подписки",
        price: 249,
        oldPrice: 399,
        discount: 37,
        rating: 4.5,
        reviews: 7800,
        image: "vk",
        badge: "popular",
        platform: "VK",
        period: "1 месяц",
        description: "VK Combo подписка"
    },
    {
        id: 107,
        name: "Кинопоиск HD",
        category: "subscriptions",
        subcategory: "video",
        categoryName: "Подписки",
        price: 299,
        oldPrice: 499,
        discount: 40,
        rating: 4.6,
        reviews: 8900,
        image: "film",
        badge: "popular",
        platform: "Кинопоиск",
        period: "1 месяц",
        description: "Кинопоиск HD подписка"
    },
    {
        id: 108,
        name: "Netflix Basic",
        category: "subscriptions",
        subcategory: "video",
        categoryName: "Подписки",
        price: 699,
        oldPrice: 999,
        discount: 30,
        rating: 4.8,
        reviews: 4500,
        image: "netflix",
        badge: "new",
        platform: "Netflix",
        period: "1 месяц",
        description: "Netflix базовая подписка"
    },
    {
        id: 109,
        name: "Spotify Premium",
        category: "subscriptions",
        subcategory: "music",
        categoryName: "Подписки",
        price: 399,
        oldPrice: 699,
        discount: 42,
        rating: 4.7,
        reviews: 6700,
        image: "spotify",
        badge: "popular",
        platform: "Spotify",
        period: "1 месяц",
        description: "Spotify Premium подписка"
    },
    {
        id: 110,
        name: "Apple Music",
        category: "subscriptions",
        subcategory: "music",
        categoryName: "Подписки",
        price: 299,
        oldPrice: 499,
        discount: 40,
        rating: 4.6,
        reviews: 3400,
        image: "apple",
        badge: "new",
        platform: "Apple",
        period: "1 месяц",
        description: "Apple Music подписка"
    },
    {
        id: 111,
        name: "YouTube Premium",
        category: "subscriptions",
        subcategory: "video",
        categoryName: "Подписки",
        price: 399,
        oldPrice: 699,
        discount: 42,
        rating: 4.8,
        reviews: 12300,
        image: "youtube",
        badge: "popular",
        platform: "YouTube",
        period: "1 месяц",
        description: "YouTube Premium подписка"
    },
    {
        id: 112,
        name: "Twitch Turbo",
        category: "subscriptions",
        subcategory: "video",
        categoryName: "Подписки",
        price: 499,
        oldPrice: 799,
        discount: 37,
        rating: 4.5,
        reviews: 2300,
        image: "twitch",
        badge: "new",
        platform: "Twitch",
        period: "1 месяц",
        description: "Twitch Turbo подписка"
    },
    {
        id: 113,
        name: "Wink Premium",
        category: "subscriptions",
        subcategory: "video",
        categoryName: "Подписки",
        price: 399,
        oldPrice: 699,
        discount: 42,
        rating: 4.4,
        reviews: 1800,
        image: "tv",
        badge: "new",
        platform: "Wink",
        period: "1 месяц",
        description: "Wink Premium подписка"
    },
    {
        id: 114,
        name: "more.tv",
        category: "subscriptions",
        subcategory: "video",
        categoryName: "Подписки",
        price: 299,
        oldPrice: 499,
        discount: 40,
        rating: 4.3,
        reviews: 1200,
        image: "tv",
        badge: "sale",
        platform: "more.tv",
        period: "1 месяц",
        description: "more.tv подписка"
    },
    {
        id: 115,
        name: "Иви Premium",
        category: "subscriptions",
        subcategory: "video",
        categoryName: "Подписки",
        price: 349,
        oldPrice: 599,
        discount: 41,
        rating: 4.5,
        reviews: 5600,
        image: "film",
        badge: "popular",
        platform: "Иви",
        period: "1 месяц",
        description: "Иви Premium подписка"
    },
    {
        id: 116,
        name: "Okko Premium",
        category: "subscriptions",
        subcategory: "video",
        categoryName: "Подписки",
        price: 399,
        oldPrice: 699,
        discount: 42,
        rating: 4.5,
        reviews: 4300,
        image: "film",
        badge: "popular",
        platform: "Okko",
        period: "1 месяц",
        description: "Okko Premium подписка"
    },
    {
        id: 117,
        name: "Amediateka",
        category: "subscriptions",
        subcategory: "video",
        categoryName: "Подписки",
        price: 499,
        oldPrice: 799,
        discount: 37,
        rating: 4.6,
        reviews: 3200,
        image: "film",
        badge: "popular",
        platform: "Amediateka",
        period: "1 месяц",
        description: "Amediateka подписка"
    },
    {
        id: 118,
        name: "START",
        category: "subscriptions",
        subcategory: "video",
        categoryName: "Подписки",
        price: 399,
        oldPrice: 599,
        discount: 33,
        rating: 4.4,
        reviews: 2100,
        image: "film",
        badge: "new",
        platform: "START",
        period: "1 месяц",
        description: "START подписка"
    },
    {
        id: 119,
        name: "Premier",
        category: "subscriptions",
        subcategory: "video",
        categoryName: "Подписки",
        price: 299,
        oldPrice: 499,
        discount: 40,
        rating: 4.3,
        reviews: 1800,
        image: "film",
        badge: "sale",
        platform: "Premier",
        period: "1 месяц",
        description: "Premier подписка"
    },
    {
        id: 120,
        name: "VK Музыка",
        category: "subscriptions",
        subcategory: "music",
        categoryName: "Подписки",
        price: 169,
        oldPrice: 299,
        discount: 43,
        rating: 4.4,
        reviews: 8900,
        image: "music",
        badge: "popular",
        platform: "VK",
        period: "1 месяц",
        description: "VK Музыка подписка"
    }
];

// Программы (20 программ)
const software = [
    {
        id: 201,
        name: "Microsoft Office 2024 Pro",
        category: "software",
        subcategory: "office",
        categoryName: "Программы",
        price: 3990,
        oldPrice: 7990,
        discount: 50,
        rating: 4.9,
        reviews: 12500,
        image: "file-alt",
        badge: "popular",
        platform: "Windows/Mac",
        description: "Word, Excel, PowerPoint, Outlook, Access"
    },
    {
        id: 202,
        name: "Microsoft Office 2021 Pro",
        category: "software",
        subcategory: "office",
        categoryName: "Программы",
        price: 2990,
        oldPrice: 5990,
        discount: 50,
        rating: 4.8,
        reviews: 8900,
        image: "file-alt",
        badge: "sale",
        platform: "Windows/Mac",
        description: "Word, Excel, PowerPoint, Outlook"
    },
    {
        id: 203,
        name: "Microsoft Office 365",
        category: "software",
        subcategory: "office",
        categoryName: "Программы",
        price: 2490,
        oldPrice: 4990,
        discount: 50,
        rating: 4.7,
        reviews: 6700,
        image: "cloud",
        badge: "popular",
        platform: "Windows/Mac",
        period: "1 год",
        description: "Office 365 подписка на 1 год"
    },
    {
        id: 204,
        name: "Adobe Photoshop 2024",
        category: "software",
        subcategory: "graphics",
        categoryName: "Программы",
        price: 2990,
        oldPrice: 5990,
        discount: 50,
        rating: 4.8,
        reviews: 3420,
        image: "paint-brush",
        badge: "popular",
        platform: "Windows/Mac",
        description: "Профессиональный редактор изображений"
    },
    {
        id: 205,
        name: "Adobe Premiere Pro 2024",
        category: "software",
        subcategory: "graphics",
        categoryName: "Программы",
        price: 3490,
        oldPrice: 6990,
        discount: 50,
        rating: 4.7,
        reviews: 2800,
        image: "video",
        badge: "popular",
        platform: "Windows/Mac",
        description: "Профессиональный видеоредактор"
    },
    {
        id: 206,
        name: "Adobe Illustrator 2024",
        category: "software",
        subcategory: "graphics",
        categoryName: "Программы",
        price: 2990,
        oldPrice: 5990,
        discount: 50,
        rating: 4.7,
        reviews: 2300,
        image: "pen",
        badge: "popular",
        platform: "Windows/Mac",
        description: "Векторная графика и иллюстрации"
    },
    {
        id: 207,
        name: "Adobe After Effects 2024",
        category: "software",
        subcategory: "graphics",
        categoryName: "Программы",
        price: 3490,
        oldPrice: 6990,
        discount: 50,
        rating: 4.7,
        reviews: 2100,
        image: "film",
        badge: "popular",
        platform: "Windows/Mac",
        description: "Создание видеоэффектов и анимации"
    },
    {
        id: 208,
        name: "CorelDRAW Graphics Suite",
        category: "software",
        subcategory: "graphics",
        categoryName: "Программы",
        price: 3290,
        oldPrice: 6590,
        discount: 50,
        rating: 4.6,
        reviews: 1500,
        image: "pen",
        badge: "popular",
        platform: "Windows",
        description: "Графический дизайн и верстка"
    },
    {
        id: 209,
        name: "Visual Studio 2024 Pro",
        category: "software",
        subcategory: "development",
        categoryName: "Программы",
        price: 4490,
        oldPrice: 8990,
        discount: 50,
        rating: 4.8,
        reviews: 5600,
        image: "code",
        badge: "new",
        platform: "Windows",
        description: "Среда разработки от Microsoft"
    },
    {
        id: 210,
        name: "JetBrains IntelliJ IDEA",
        category: "software",
        subcategory: "development",
        categoryName: "Программы",
        price: 2490,
        oldPrice: 4990,
        discount: 50,
        rating: 4.9,
        reviews: 3400,
        image: "java",
        badge: "popular",
        platform: "Windows/Mac/Linux",
        description: "IDE для Java разработки"
    },
    {
        id: 211,
        name: "PyCharm Professional",
        category: "software",
        subcategory: "development",
        categoryName: "Программы",
        price: 1990,
        oldPrice: 3990,
        discount: 50,
        rating: 4.8,
        reviews: 2900,
        image: "python",
        badge: "popular",
        platform: "Windows/Mac/Linux",
        description: "IDE для Python разработки"
    },
    {
        id: 212,
        name: "VMware Workstation Pro",
        category: "software",
        subcategory: "development",
        categoryName: "Программы",
        price: 2990,
        oldPrice: 5990,
        discount: 50,
        rating: 4.7,
        reviews: 1100,
        image: "server",
        badge: "professional",
        platform: "Windows/Linux",
        description: "Виртуализация ОС"
    },
    {
        id: 213,
        name: "Microsoft Project 2024",
        category: "software",
        subcategory: "office",
        categoryName: "Программы",
        price: 2990,
        oldPrice: 5990,
        discount: 50,
        rating: 4.5,
        reviews: 800,
        image: "tasks",
        badge: "professional",
        platform: "Windows",
        description: "Управление проектами"
    },
    {
        id: 214,
        name: "MATLAB R2024",
        category: "software",
        subcategory: "development",
        categoryName: "Программы",
        price: 5990,
        oldPrice: 11990,
        discount: 50,
        rating: 4.6,
        reviews: 950,
        image: "calculator",
        badge: "professional",
        platform: "Windows/Mac/Linux",
        description: "Численные вычисления и моделирование"
    },
    {
        id: 215,
        name: "AutoCAD 2024",
        category: "software",
        subcategory: "graphics",
        categoryName: "Программы",
        price: 4990,
        oldPrice: 9990,
        discount: 50,
        rating: 4.6,
        reviews: 1800,
        image: "draw-polygon",
        badge: "professional",
        platform: "Windows",
        description: "САПР для проектирования"
    },
    {
        id: 216,
        name: "3ds Max 2024",
        category: "software",
        subcategory: "graphics",
        categoryName: "Программы",
        price: 5490,
        oldPrice: 10990,
        discount: 50,
        rating: 4.5,
        reviews: 1200,
        image: "cube",
        badge: "professional",
        platform: "Windows",
        description: "3D моделирование и анимация"
    },
    {
        id: 217,
        name: "SolidWorks 2024",
        category: "software",
        subcategory: "graphics",
        categoryName: "Программы",
        price: 6990,
        oldPrice: 13990,
        discount: 50,
        rating: 4.7,
        reviews: 800,
        image: "cubes",
        badge: "professional",
        platform: "Windows",
        description: "3D проектирование
